[package]
name = "fuse-taskchampion"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["cargo", "derive"] }
env_logger = "0.11.8"
fuser = { version = "0.16.0" }
libc = "0.2.178"
pulldown-cmark = "0.13.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "macros"] }
taskchampion = "2.0.3"
tokio = { version = "1.48.0", features = ["full"] }
