[package]
name = "recipt-printer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
escpos = { version = "0.17.0", features = ["full"] }
image = { version = "0.25.0-preview.0" }
pulldown-cmark = "0.13.0"
rusb = "0.9"
