[package]
name = "esp32-train-time"
version = "0.1.0"
edition = "2021"

[dependencies]
hd44780-driver = "0.4.0"
heapless = "0.8.0"
embedded-io-async = "0.6.1"
static_cell = "2.1"
esp-hal = { version = "1.0.0", features = ["esp32c3", "unstable"] }
esp-backtrace = { version = "0.18.1", features = ["esp32c3", "panic-handler", "println"] }
esp-println = { version = "0.16.1", features = ["esp32c3", "log-04"] }
esp-radio = { version = "0.17.0", features = ["esp32c3", "wifi"] }
esp-rtos = { version = "0.2.0", features = ["esp32c3", "embassy", "esp-radio"] }
embassy-time = "0.4"
embassy-executor = { version = "0.9.1", features = ["arch-riscv32"] }
embassy-net = { version = "0.7.1", features = ["tcp", "udp", "dhcpv4", "medium-ethernet"] }
minimq = "0.10.0"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
lto = "fat"
