[package]
name = "actix-webserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0"
actix-files = "0.6.0"
lazy_static = "1.4.0"
serde = { version = "1.0.204", features = ["derive"] }
